site_name: ESPRI-MOD Documentation

nav:
  - Home: index.md
  - ESGF: 
    - ESGF-Ansible:
      - Legacy Upgrade: esgf/ansible_legacy_upgrade.md
      - Upgrade : esgf/ansible_upgrade.md
  - ES-DOC:
    - Errata:
      - Web Service: esdoc/errata/ws.md
      - PID Service: esdoc/errata/pid.md
      - Front End: esdoc/errata/fe.md
      - Client Tool: esdoc/errata/client.md    
    - Front Ends:
        - Search: esdoc/fe/search.md
        - Explore: esdoc/fe/explorer.md
    - Web Services: esdoc/web_services.md
  - HERMES:
    - Data Base: hermes/db.md
    - Message Broker: hermes/mq.md
    - Web Site: hermes/web.md

theme: cinder

markdown_extensions:
  - markdown.extensions.admonition
  - markdown.extensions.footnotes
  - pymdownx.details
  - markdown.extensions.codehilite :
     guess_lang :  true 

use_directory_urls: false