site_name: ESPRI-MOD Documentation

nav:
  - Home: index.md
  - ESGF: 
    - ESGF-Ansible:
      - Installation: esgf/ansible_installation.md
      - Fresh install without backups: esgf/fresh_install_data_node.md
      - Upgrade : esgf/ansible_upgrade.md
      - Migration: esgf/migration_centos_7.md
    - ESGF administration:
      - Machine Setup : esgf/machine_setup.md
      - Certificates Management : esgf/cert_mgmt.md
      - Testing : esgf/testing.md
      - Periodic Tasks: esgf/periodic_tasks.md
      - Troubleshooting: esgf/troubleshooting.md
      - In case of power cuts and more: esgf/maintenance_cases.md
      - What to do when rebooting machines: esgf/how_to_reboot.md
    - ESGF-Docker:
      - Installation via Docker: esgf/docker_installation.md
  - ES-DOC:
    - Errata:
      - Web Service: esdoc/errata/ws.md
      - PID Service: esdoc/errata/pid.md
      - Front End: esdoc/errata/fe.md
      - Client Tool: esdoc/errata/client.md    
    - Front Ends:
        - Search: esdoc/fe/search.md
        - Explore: esdoc/fe/explorer.md
    - Web Services: esdoc/web_services.md
  - HERMES:
    - Data Base: hermes/db.md
    - Message Broker: hermes/mq.md
    - Web Site: hermes/web.md
    - Maintenance: hermes/maintenance.md
  - WPS pour projet Copernicus:
    - Installation: wps-copernicus/installation.md
    - Usage of birdy to fetch datasests: wps-copernicus/fetch_models.md
    - Docker: wps-copernicus/docker.md
    - Maintenance: wps-copernicus/maintenance.md
  - SYNDA:
      - Synda: synda/synda.md

theme: 
  name: material 
  palette:
    primary: 'Blue'
    language: 'en'
  feature:
    tabs: true

markdown_extensions:
  - codehilite:
      guess_lang: false
  - admonition
  - footnotes
  - pymdownx.details
  - pymdownx.inlinehilite
  - pymdownx.mark
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg

use_directory_urls: false
